import type { Metadata } from "next";
import "./globals.css";
import { SideBar } from "./components/layout/SideBar";

export const metadata: Metadata = {
  title: "Aurora Prep Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-gray-50">
      <body className="grid grid-cols-[1fr_4fr]">
        <SideBar />
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
}
